#!/usr/bin/env node
/**
 * export_lods.js: generate the mesh list for uncook_lods.wscript.
 *
 * The original export called `wkit.UncookMesh(path, dir, false)` and stopped
 * there. The signature is
 *
 *     UncookMesh(path[, outputDir, withMaterials, lodFilter, gltfBinary])
 *
 * and `lodFilter` defaults to LOD0 only, so all 32,851 GLBs on disk carry the
 * game's highest detail and none of the LODs CDPR authored beneath it. On one
 * building's 51-mesh kit those LODs are 26,143 / 8,819 / 1,526 triangles: a
 * third and then a seventeenth of what is being drawn today.
 *
 * The list is generated rather than written by hand for the same reason
 * uncook_remaining.js exists: the V8 host inside WolvenKit cannot read the
 * filesystem, so anything that depends on what is on disk happens out here.
 *
 * RESUMABLE, because 32,859 meshes do not fit in one run_wscript window.
 * Anything already sitting in the all-LOD root is dropped from the list, so
 * the loop is: generate, run, generate, run, until the list comes back empty.
 * The same split uncook_remaining.js uses, for the same reason: the V8 host
 * inside WolvenKit cannot see the filesystem.
 *
 * Usage:
 *   node scripts/wkit/export_lods.js data/mesh-export-list.json
 *   node scripts/wkit/export_lods.js data/spike--8_0_0_L2-298522-all.json
 *   node scripts/wkit/export_lods.js data/mesh-export-list.json --all
 *
 * Writes: scripts/wkit/ncz_lod_meshes.wscript
 */
'use strict';

const fs = require('fs');
const path = require('path');

const args = process.argv.slice(2);
const li = args.indexOf('--list');
const source = li >= 0 ? args[li + 1] : args[0];

if (!source) {
  console.error('usage: node scripts/wkit/export_lods.js <spike json | mesh list json>');
  process.exit(1);
}

const raw = JSON.parse(fs.readFileSync(source, 'utf8'));
// A spike bundle (meshes[].depot), the full export list (meshList[].path), or
// a bare array of paths. Three shapes because the list is wanted at three
// scales: one building, one district, the whole city.
const meshes = Array.isArray(raw) ? raw
  : Array.isArray(raw.meshList) ? raw.meshList.map(m => m.path || m)
    : Array.isArray(raw.meshes) ? raw.meshes.map(m => m.depot || m)
      : null;
if (!meshes || !meshes.length) {
  console.error(`no mesh paths in ${source}`);
  process.exit(1);
}

const LOD_ROOT = 'd:\\Modding\\CP2077 Mods\\MyMods\\map_data_export\\source\\raw_alllod';
const all = [...new Set(meshes)];
// Skip what is already exported unless --all is passed. A GLB on disk is the
// only resume state there is, and it is the honest one: the run that wrote it
// is over and nothing needs to remember how far it got.
const uniq = args.includes('--all') ? all
  : all.filter(p => !fs.existsSync(path.join(LOD_ROOT, p.replace(/\.mesh$/i, '.glb'))));

const out = path.join(__dirname, 'ncz_lod_meshes.wscript');
// JSON.stringify escapes the backslashes in a depot path correctly. Building
// this string by hand, or piping it through a shell, is how the last three
// backslash incidents happened.
fs.writeFileSync(out,
  '// GENERATED by scripts/wkit/export_lods.js. Do not edit.\n' +
  `// ${uniq.length} meshes, from ${path.basename(source)}\n` +
  `export const LOD_MESHES = ${JSON.stringify(uniq, null, 2)};\n`);

console.log(`${uniq.length} of ${all.length} meshes still to export -> ${path.relative(process.cwd(), out)}`);
if (!uniq.length) console.log('nothing left: the all-LOD export is complete');
else console.log('now run scripts/wkit/uncook_lods.wscript through run_wscript, then run this again');
