#!/usr/bin/env node
/**
 * export_lods.js: generate the mesh list for uncook_lods.wscript.
 *
 * The original export called `wkit.UncookMesh(path, dir, false)` and stopped
 * there. The signature is
 *
 *     UncookMesh(path[, outputDir, withMaterials, lodFilter, gltfBinary])
 *
 * and `lodFilter` defaults to LOD0 only, so all 32,851 GLBs on disk carry the
 * game's highest detail and none of the LODs CDPR authored beneath it. On one
 * building's 51-mesh kit those LODs are 26,143 / 8,819 / 1,526 triangles: a
 * third and then a seventeenth of what is being drawn today.
 *
 * The list is generated rather than written by hand for the same reason
 * uncook_remaining.js exists: the V8 host inside WolvenKit cannot read the
 * filesystem, so anything that depends on what is on disk happens out here.
 *
 * Usage:
 *   node scripts/wkit/export_lods.js data/spike--8_0_0_L2-298522-all.json
 *   node scripts/wkit/export_lods.js --list mylist.json
 *
 * Writes: scripts/wkit/ncz_lod_meshes.wscript
 */
'use strict';

const fs = require('fs');
const path = require('path');

const args = process.argv.slice(2);
const li = args.indexOf('--list');
const source = li >= 0 ? args[li + 1] : args[0];

if (!source) {
  console.error('usage: node scripts/wkit/export_lods.js <spike json | mesh list json>');
  process.exit(1);
}

const raw = JSON.parse(fs.readFileSync(source, 'utf8'));
// Accept either a spike bundle (meshes[].depot) or a bare array of paths.
const meshes = Array.isArray(raw) ? raw
  : Array.isArray(raw.meshes) ? raw.meshes.map(m => m.depot || m)
    : null;
if (!meshes || !meshes.length) {
  console.error(`no mesh paths in ${source}`);
  process.exit(1);
}

const uniq = [...new Set(meshes)];
const out = path.join(__dirname, 'ncz_lod_meshes.wscript');
// JSON.stringify escapes the backslashes in a depot path correctly. Building
// this string by hand, or piping it through a shell, is how the last three
// backslash incidents happened.
fs.writeFileSync(out,
  '// GENERATED by scripts/wkit/export_lods.js. Do not edit.\n' +
  `// ${uniq.length} meshes, from ${path.basename(source)}\n` +
  `export const LOD_MESHES = ${JSON.stringify(uniq, null, 2)};\n`);

console.log(`${uniq.length} meshes -> ${path.relative(process.cwd(), out)}`);
console.log('now run scripts/wkit/uncook_lods.wscript through run_wscript');
