// export_building_meshes.wscript — WolvenKit
// ─────────────────────────────────────────────────────────────────────────────
// EXTRACT, THEN EXPORT, THEN CHECK FROM OUTSIDE. Every mesh placed inside a
// district -> GLB, so the box-cloud rebuild can voxelise real triangles instead
// of bounding boxes.
//
// WHY. The rebuild voxelises one box per placement, so a Corpo Plaza proxy
// carrying 10,358 triangles across 608 m becomes a single rectangle. Real
// triangles keep the building's shape, and keep its rotation with it: a
// transformed triangle is already oriented, so nothing has to infer a yaw.
//
// The list is data/mesh-export-list.txt, generated by
// scripts/mesh_export_list.js and shipped beside this file as
// ncz_mesh_list.wscript. It holds every distinct mesh placed inside a
// district's true trigger boundary, ordered LARGEST FIRST so an interrupted run
// leaves the geometry that matters most already on disk.
//
// ─── RESUMABLE, BECAUSE THIS RUNS FOR HOURS ──────────────────────────────────
// A mesh whose .glb is already in raw is skipped, so the script can be run
// again after an interruption and will pick up where it stopped. Re-running it
// after a game patch re-exports nothing unless the raw folder is cleared.
//
// ─── AND IT DOES NOT CHECK ITS OWN WORK ──────────────────────────────────────
// `wkit.ExportFiles()` is ASYNCHRONOUS. It returns before it has written
// anything, and a wscript cannot sleep, so any count taken here is a lie: the
// glass export reported "ONLY 798/2257 EXIST" 0.9 seconds in and nothing was
// wrong. Verify from outside, once the count has STOPPED CHANGING, with
//   node scripts/wkit/check_export.js --expect <n>
// which counts files written DURING the run rather than the total, because an
// overwrite does not move a total and a long run of overwrites looks exactly
// like a finished export.
import * as Logger from 'Logger.wscript';
import { MESHES } from 'ncz_mesh_list.wscript';

// EXTRACTION is batched only to report progress; it is synchronous and safe to
// call repeatedly.
//
// EXPORT IS ONE CALL, and must stay one call. Queuing it per batch put 58
// asynchronous exports in flight in 43 seconds and they raced: 28,870 files
// extracted with zero failures, and 62 GLBs written. The glass export ran a
// single ExportFiles over 4,509 files and wrote all of them. Progress comes
// from check_export.js watching the directory, not from splitting this call.
const BATCH = 500;

Logger.Info(`[ncz] export list: ${MESHES.length} meshes`);

// ─── 1. What is already on disk ──────────────────────────────────────────────
const todo = [];
let already = 0;
for (const p of MESHES) {
  let have = false;
  try { have = wkit.FileExistsInRaw(p.replace(/\.mesh$/i, '.glb')); } catch { have = false; }
  if (have) already++; else todo.push(p);
}
Logger.Info(`[ncz] ${already} already exported, ${todo.length} to do`);
if (!todo.length) {
  Logger.Success('[ncz] nothing to do: every mesh on the list is already in raw.');
} else {

// ─── 2. Extract into the project, then export ────────────────────────────────
// ExportFiles works on PROJECT files. Handed an archive path it logs
// "doesn't exist in the project. Skipping", and a skip is not a throw, so a
// try/catch sees nothing and the run reports success having written zero files.
let added = 0, addFail = 0;
for (let i = 0; i < todo.length; i += BATCH) {
  const slice = todo.slice(i, i + BATCH);
  for (const p of slice) {
    try { wkit.Extract(p); added++; }
    catch (e) {
      addFail++;
      if (addFail <= 5) Logger.Error(`[ncz] Extract failed: ${p} :: ${e}`);
    }
  }
  Logger.Info(`[ncz] extracted ${Math.min(i + BATCH, todo.length)}/${todo.length}`);
}
Logger.Info(`[ncz] extracted ${added}, extract failures ${addFail}`);

// ONE call. See the note on BATCH above.
try { wkit.ExportFiles(todo); Logger.Info(`[ncz] ExportFiles queued for ${todo.length} meshes`); }
catch (e) { Logger.Error(`[ncz] ExportFiles threw: ${e}`); }
Logger.Warning('[ncz] ExportFiles is ASYNCHRONOUS. Nothing above proves a file was written.');
Logger.Warning(`[ncz] VERIFY: node scripts/wkit/check_export.js --expect ${MESHES.length}`);

}
