// export_building_meshes.wscript — WolvenKit
// ─────────────────────────────────────────────────────────────────────────────
// EXTRACT, THEN EXPORT, THEN CHECK FROM OUTSIDE. Every mesh placed inside a
// district -> GLB, so the box-cloud rebuild can voxelise real triangles instead
// of bounding boxes.
//
// WHY. The rebuild voxelises one box per placement, so a Corpo Plaza proxy
// carrying 10,358 triangles across 608 m becomes a single rectangle. Real
// triangles keep the building's shape, and keep its rotation with it: a
// transformed triangle is already oriented, so nothing has to infer a yaw.
//
// The list is data/mesh-export-list.txt, generated by
// scripts/mesh_export_list.js and shipped beside this file as
// ncz_mesh_list.wscript. It holds every distinct mesh placed inside a
// district's true trigger boundary, ordered LARGEST FIRST so an interrupted run
// leaves the geometry that matters most already on disk.
//
// ─── RESUMABLE, BECAUSE THIS RUNS FOR HOURS ──────────────────────────────────
// A mesh whose .glb is already in raw is skipped, so the script can be run
// again after an interruption and will pick up where it stopped. Re-running it
// after a game patch re-exports nothing unless the raw folder is cleared.
//
// ─── AND IT DOES NOT CHECK ITS OWN WORK ──────────────────────────────────────
// `wkit.ExportFiles()` is ASYNCHRONOUS. It returns before it has written
// anything, and a wscript cannot sleep, so any count taken here is a lie: the
// glass export reported "ONLY 798/2257 EXIST" 0.9 seconds in and nothing was
// wrong. Verify from outside, once the count has STOPPED CHANGING, with
//   node scripts/wkit/check_export.js --expect <n>
// which counts files written DURING the run rather than the total, because an
// overwrite does not move a total and a long run of overwrites looks exactly
// like a finished export.
import * as Logger from 'Logger.wscript';
import { MESHES } from 'ncz_mesh_list.wscript';

// EXTRACTION is batched only to report progress; it is synchronous and safe to
// call repeatedly.
const BATCH = 500;

// ONE ExportFiles CALL PER RUN, AND A BOUNDED ONE. Two failure modes were
// measured, and MAX_PER_RUN is the shape that avoids both:
//
//   Split into 58 calls of 500: all 58 go in flight inside 43 seconds and race.
//   28,870 extracted with zero failures, 62 GLBs written.
//
//   One call over all 28,870: WolvenKit stops responding, no further script
//   can be run, and the project has to be killed. 21 GLBs written.
//
// The glass export ran a single call over 4,509 and wrote all of them, so that
// is the size known to work. The list is ordered largest mesh first and the
// run is resumable, so each run takes the next chunk of the most valuable
// geometry and the whole set arrives over several runs.
const MAX_PER_RUN = 4000;

Logger.Info(`[ncz] export list: ${MESHES.length} meshes`);

// ─── 1. What is already on disk ──────────────────────────────────────────────
const todo = [];
let already = 0;
for (const p of MESHES) {
  let have = false;
  try { have = wkit.FileExistsInRaw(p.replace(/\.mesh$/i, '.glb')); } catch { have = false; }
  if (have) already++; else todo.push(p);
}
const remaining = todo.length;
if (todo.length > MAX_PER_RUN) todo.length = MAX_PER_RUN;
Logger.Info(`[ncz] ${already} already exported, ${remaining} still to do, taking ${todo.length} this run`);
if (!remaining) {
  Logger.Success('[ncz] nothing to do: every mesh on the list is already in raw.');
} else {

// ─── 2. Extract into the project, then export ────────────────────────────────
// ExportFiles works on PROJECT files. Handed an archive path it logs
// "doesn't exist in the project. Skipping", and a skip is not a throw, so a
// try/catch sees nothing and the run reports success having written zero files.
let added = 0, addFail = 0;
for (let i = 0; i < todo.length; i += BATCH) {
  const slice = todo.slice(i, i + BATCH);
  for (const p of slice) {
    try { wkit.Extract(p); added++; }
    catch (e) {
      addFail++;
      if (addFail <= 5) Logger.Error(`[ncz] Extract failed: ${p} :: ${e}`);
    }
  }
  Logger.Info(`[ncz] extracted ${Math.min(i + BATCH, todo.length)}/${todo.length}`);
}
Logger.Info(`[ncz] extracted ${added}, extract failures ${addFail}`);

// ONE call. See the note on BATCH above.
try { wkit.ExportFiles(todo); Logger.Info(`[ncz] ExportFiles queued for ${todo.length} meshes`); }
catch (e) { Logger.Error(`[ncz] ExportFiles threw: ${e}`); }
Logger.Warning('[ncz] ExportFiles is ASYNCHRONOUS. Nothing above proves a file was written.');
Logger.Warning(`[ncz] VERIFY: node scripts/wkit/check_export.js --expect ${already + todo.length}`);
if (remaining > todo.length) {
  Logger.Warning(`[ncz] ${remaining - todo.length} meshes remain. Run this again once the count settles.`);
}

}
