// signage_emissive.wscript: wolvenkit-mcp run_wscript, NOT the WolvenKit GUI
// ─────────────────────────────────────────────────────────────────────────────
// Per-mesh material data for the night scene's signage emitters.
//
// For each distinct signage mesh (ncz_signage_meshes.wscript, generated by
// scripts/extract_signage.js): appearances with their chunk materials, and per
// material the emissive parameters and area. Many signage materials emit via a
// neon template (neon_parallax.mt) with EmissiveEV 0 and a black
// EmissiveColor, so the TEMPLATE and the base-colour texture path are recorded
// alongside the scalar values; the consumer decides what "lit" means per
// template.
//
// Output: one "EM<tab>{json}" log line per mesh; scripts/extract_signage.js
// cannot call the MCP, so the collector prints and Node assembles.
import { SIGNAGE_MESHES } from 'ncz_signage_meshes.wscript';

const col = c => (c && typeof c === 'object') ? [c.Red ?? 0, c.Green ?? 0, c.Blue ?? 0] : null;

let ok = 0, failed = 0;
for (const mesh of SIGNAGE_MESHES) {
  let r;
  try { r = JSON.parse(wkit.MeshInfo(mesh, null, false, true)); }
  catch (e) { console.warn(`FAIL\t${mesh}\t${e}`); failed++; continue; }
  if (!r || r.error) { console.warn(`FAIL\t${mesh}\t${r && r.error}`); failed++; continue; }

  const areaByMat = {};
  if (r.totals && r.totals.by_material) {
    for (const m of r.totals.by_material) areaByMat[m.material] = m.surface_area_m2;
  }
  const materials = {};
  const list = (r.material_data && r.material_data.materials) || [];
  for (const m of list) {
    const d = m.Data || {};
    materials[m.Name] = {
      template: m.MaterialTemplate || null,
      ev: d.EmissiveEV ?? null,
      color: col(d.EmissiveColor),
      emissiveTex: d.Emissive || null,
      baseColorTex: d.BaseColor || null,
      area: areaByMat[m.Name] ?? null,
    };
  }
  const rec = {
    selected: r.selected_appearance || null,
    appearances: (r.appearances || []).map(a => ({ name: a.name, materials: a.chunk_materials })),
    materials,
    area: r.totals ? r.totals.surface_area_m2 : null,
  };
  console.log(`EM\t${mesh}\t${JSON.stringify(rec)}`);
  ok++;
}
console.log(`DONE ${ok} ok, ${failed} failed of ${SIGNAGE_MESHES.length}`);
