// uncook_meshes.wscript — wolvenkit-mcp run_wscript, NOT the WolvenKit GUI
// ─────────────────────────────────────────────────────────────────────────────
// HEADLESS GEOMETRY-ONLY EXPORT of every mesh still missing from raw.
//
// This replaces export_building_meshes.wscript's ExportFiles path entirely.
// wkit.UncookMesh (wolvenkit-mcp v1.8.0) is SYNCHRONOUS, writes ONE glb and
// nothing else, and returns {error} JSON instead of throwing, so the loop
// sees every result and none of the GUI failure shapes (58 racing calls,
// the >4k hang, the resource leak) can occur.
//
// The list is ncz_remaining.wscript, generated by uncook_remaining.js, which
// filters out what is already on disk BEFORE this runs: the V8 host cannot
// check the filesystem, so resumability lives outside. Regenerate between runs.
//
// TIME-BUDGETED, NOT COUNT-BUDGETED. run_wscript interrupts at
// timeout_seconds (max 1800), and an interrupt mid-write is worth avoiding:
// stop cleanly at BUDGET_MS and report where we got to. Call with
// timeout_seconds: 1800 so the budget, not the interrupt, ends the run.
import { REMAINING } from 'ncz_remaining.wscript';

const RAW = 'd:\\Modding\\CP2077 Mods\\MyMods\\map_data_export\\source\\raw';
const BUDGET_MS = 1500 * 1000;   // inside the 1800 s hard timeout
const LOG_EVERY = 500;

const t0 = Date.now();
let ok = 0, failed = 0, taken = 0;
const firstErrors = [];

console.log(`[ncz] ${REMAINING.length} meshes to uncook, budget ${BUDGET_MS / 1000}s`);

for (const p of REMAINING) {
  if (Date.now() - t0 > BUDGET_MS) break;
  taken++;
  let r;
  try { r = JSON.parse(wkit.UncookMesh(p, RAW, false)); }
  catch (e) { r = { error: String(e) }; }
  if (r && r.files && r.files.length) ok++;
  else {
    failed++;
    if (firstErrors.length < 10) firstErrors.push(`${p} :: ${r && (r.error || JSON.stringify(r))}`);
  }
  if (taken % LOG_EVERY === 0) {
    const rate = taken / ((Date.now() - t0) / 60000);
    console.log(`[ncz] ${taken}/${REMAINING.length}  ok ${ok}  failed ${failed}  ${rate.toFixed(0)}/min`);
  }
}

const mins = (Date.now() - t0) / 60000;
console.log(`[ncz] DONE this run: ${ok} written, ${failed} failed, ${taken} attempted of ${REMAINING.length} in ${mins.toFixed(1)} min`);
for (const e of firstErrors) console.warn(`[ncz] fail: ${e}`);
if (taken < REMAINING.length) {
  console.log(`[ncz] ${REMAINING.length - taken} remain. Regenerate the list (node scripts/wkit/uncook_remaining.js) and run again.`);
} else {
  console.log('[ncz] list exhausted. Verify from outside: node scripts/wkit/check_export.js');
}
