#!/usr/bin/env node
/**
 * scripts/wkit/uncook_remaining.js
 * ─────────────────────────────────────────────────────────────────────────
 * WHICH MESHES ARE STILL MISSING, AS A WSCRIPT MODULE.
 *
 * The headless exporter (uncook_meshes.wscript) runs inside the MCP's V8 host,
 * which cannot see the disk. The skip-what-exists logic therefore runs HERE,
 * where the filesystem is visible, and the wscript receives a list that is
 * already filtered. Re-run this between export runs; the wscript stays dumb.
 *
 * Reads  data/mesh-export-list.txt          (largest mesh first, keep order)
 * Scans  <raw>/<depot path>.glb             for what already exists
 * Writes scripts/wkit/ncz_remaining.wscript (gitignored, generated)
 *
 * Usage:
 *   node scripts/wkit/uncook_remaining.js
 *   node scripts/wkit/uncook_remaining.js --raw "d:/somewhere/else/raw"
 */
'use strict';
const fs = require('fs');
const path = require('path');

const arg = (f, d) => (process.argv.includes(f) ? process.argv[process.argv.indexOf(f) + 1] : d);
const RAW = arg('--raw', 'd:/Modding/CP2077 Mods/MyMods/map_data_export/source/raw');
const LIST = path.join(__dirname, '..', '..', 'data', 'mesh-export-list.txt');
const OUT = path.join(__dirname, 'ncz_remaining.wscript');

const all = fs.readFileSync(LIST, 'utf8').split('\n').map(s => s.trim()).filter(Boolean);

const remaining = [];
let have = 0;
for (const p of all) {
  const glb = path.join(RAW, p.replace(/\.mesh$/i, '.glb'));
  if (fs.existsSync(glb)) have++;
  else remaining.push(p);
}

fs.writeFileSync(OUT,
  '// GENERATED by scripts/wkit/uncook_remaining.js. Do not hand-edit.\n' +
  `// ${remaining.length} of ${all.length} meshes still missing from raw.\n` +
  'export const REMAINING = [\n' +
  remaining.map(p => `  ${JSON.stringify(p)},`).join('\n') +
  '\n];\n');

console.log(`list ${all.length.toLocaleString()}  on disk ${have.toLocaleString()}  remaining ${remaining.length.toLocaleString()}`);
console.log(`wrote ${OUT}`);
console.log(`next: run_wscript scripts/wkit/uncook_meshes.wscript (timeout_seconds 1800)`);
